const C = {
    SELECT_TAG: 'SELECT_TAG',
    DESELECT_TAG: 'DESELECT_TAG',
    RENAME_TAG: 'RENAME_TAG',
    INSERT_TAG: 'INSERT_TAG',
    INSERT_TAG_TEXT: 'INSERT_TAG_TEXT',
    DELETE_TAG: 'DELETE_TAG',
    DELETE_TAG_TEXT: 'DELETE_TAG_TEXT',
    CUT_TAGS: 'CUT_TAGS',
    COPY_TAGS: 'COPY_TAGS',
    PASTE_TAGS: 'PASTE_TAGS',
    PASTE_TAGS_TEXT: 'PASTE_TAGS_TEXT',
    WRAP_TAGS: 'WRAP_TAGS',
    UNWRAP_TAGS: 'UNWRAP_TAGS',
    ADD_ATTRIBUTE: 'ADD_ATTRIBUTE',
    EDIT_ATTRIBUTE: 'EDIT_ATTRIBUTE',
    DELETE_ATTRIBUTE: 'DELETE_ATTRIBUTE',
    EDIT_TEXT: 'EDIT_TEXT',
}

export default C