export const Colors = {
    NodeColor: 'sienna',
    NodeBracketColor: 'darkgreen',
    NSColor: 'red',
    NameColor: 'blue',
    NodeSeparatorColor: 'black',
    NodeToggleColor: 'navy',
    AttributeColor: 'sienna',
    AttributeNSColor: 'rgb(204, 4, 204)',
    AttributeSeparatorColor: 'black',
    AttributeNameColor: 'rgb(180, 24, 3)',
    AttributeValueColor: 'rgb(5, 197, 181)',
    AttributeToggleColor: 'purple',
    AttributeAtSignColor: 'magenta',
    CDATAHeadingColor: 'rgb(104, 10, 4)',
    CDATALabelColor: 'magenta',
    CDATABodyColor: 'orange',
    CDATAToggleColor: 'brown',
    CommentHeadingColor: 'olive',
    CommentBodyColor: 'rgb(7, 201, 33)',
    CommentToggleColor: 'brown',
    PIHeadingColor: 'olive',
    PILangColor: 'darkorange',
    PIBodyColor: 'darkgreen',
    PIToggleColor: 'brown',
    TextColor: 'black',
    TextToggleColor: 'brown',
    TextBracketColor: 'navy',
    PrefixColor: 'olive',
    IsDeletedColor: 'green',
    NotDeletedColor: 'red',
    TextInputBackgroundColor: 'none',
    TextInputBorderColor: '#ccc',
    TextAreaBackgroundColor: 'none',
    TextAreaBorderColor: '#ccc',
    PrefixButtonShowColor: 'red',
    PrefixButtonHideColor: 'transparent',
    SelectedBackgroundColor: '#ccffcc',
    UnselectedBackgroundColor: 'transparent',
    OddColor: '#eee',
    EvenColor: '#fff',
}

export const ButtonStyles = {
    height: '1.5em',
	width: 'auto',
	padding: '.1em .5em',
	border: 'none',
	borderRadius: '.25em',
	backgroundImage: 'linear-gradient(to bottom, #57b, #148)',
  	boxShadow: '0.1em 0.1em 0.5em #124',
	font: 'Arial, Helvetica, sans-serif',
	fontWeight: 'bold',
	fontSize: '0.6rem',
    color: 'white',
}

export const PanelButtonsRight = {
    width: '6em',
    marginRight: '.4em',
}

export const CheckboxStyles = {
    height: '1em',
    width: '1em',
}

export const Styles = {
    TextInputBorderWidth: '1px',
    TextInputBorderRadius: '4px',
    TextInputFont: 'inherit',
    TextInputFontWeight: 'bold',
    TextInputHeight: '1.5em',
    TextInputWidth: '20em',

    TextAreaBorderWidth: '1px',
    TextAreaBorderRadius: '4px',
    TextAreaFont: 'inherit',
    TextAreaFontWeight: 'bold',
    TextAreaHeight: 'auto',
    TextAreaMinHeight: '500px',
    TextAreaWidth: '100%',

    TextViewMaxWidth: '500px',
}

export const Symbols = {
    NodeOpenStartCaret: "<",
    NodeOpenEndCaret: ">",
    NodeCloseStartCaret: "</",
    NodeCloseEndCaret: ">",
    NodeEmptyEndCaret: "/>",
    NodeNSSeparator: ":",
    NodeToggleOpen: " +",
    NodeToggleClose: " -",
    AttributePrefixOff: "   ",
    AttributePrefixOn: " | ",
    AttributeQuote: '"',
    AttributeEquals: "=",
    AttributeNSSeparator: ":",
    AttributeToggleOpen: "+",
    AttributeToggleClose: "-",
    AttributeOpenBracket: "[",
    AttributeAtSign: "@",
    AttributeCloseBracket: "]",
    TextToggleOpen: " -",
    TextToggleClose: " +",
    TextOpenBracket: "[",
    TextCloseBracket: "]",
    TextQuote: '"',
    TextElipsis: "...",
    CDATAOpenBracketStart: "<![",
    CDATAOpenBracketLabel: "CDATA",
    CDATAOpenBracketEnd: "[",
    CDATACloseBracket: "]]>",
    CDATAToggleOpen: " -",
    CDATAToggleClose: " +",
    CommentOpenBracket: "<!--",
    CommentCloseBracket: "-->",
    CommentToggleOpen: " -",
    CommentToggleClose: " +",
    CommentLabel: "Comment",
    PIOpenBracket: "<?",
    PICloseBracket: "?>",
    PIToggleOpen: " -",
    PIToggleClose: " +",
    DeleteIsDeleted:"+",
    DeleteNotDeleted:"𐄂",
    ButtonInsert:"+",
    ButtonEdit:"&#x1F589;",
    ButtonSave:"✓",
    ButtonCancel:"𐄂",
    PrefixOn: " |",
    PrefixOff: "  ",
    PathSeparator: "/",
    ArrowRight: "▸",
    ArrowDown: "▾",
    ArrowUp: "▴",
    ArrowLeft: "◂",
    ToggleOpen: " -",
    ToggleClose: " +"
}

export const Sizes = {
    NSSize: 4,
    NSMaxLength: 20,
    NameSize: 20,
    NameMaxLength: 100,
    TextPreviewLength: 40,
    PISize: 12,
    PIMaxLength: 12,
    TextPathLength: 10,
}

export const Editors = {
    NODE_EDITOR: "NODE_EDITOR",
    TEXT_EDITOR: "TEXT_EDITOR",
    CDATA_EDITOR: "CDATA_EDITOR",
    COMMENT_EDITOR: "COMMENT_EDITOR",
    PI_EDITOR: "PI_EDITOR",
    XML_DISPLAY: "XML_DISPLAY",
    CLIPBOARD: "CLIPBOARD",
}

export const Labels = {
    NewElementMode: "Element",
    SaveElement: "Save",
    CancelElement: "Cancel",
    UnwrapElement: "Unwrap",
    NewAttribute: "New",
    SaveAttribute: "Save",
    CancelAttribute: "Cancel",
    DeleteAttribute: "Delete",
    UndeleteAttribute: "Undelete",
    NewCDATAMode: "CDATA",
    NewCommentMode: "Comment",
    NewPIMode: "PI",
    SaveText: "Save",
    CancelText: "Cancel",
    InsertNodeText: "Insert",
    CancelNodeText: "Cancel",
    InsertCDATA: "Insert CDATA",
    SaveCDATA: "Save",
    CancelCDATA: "Cancel",
    UnwrapCDATA: "Unwrap",
    InsertComment: "Insert Comment",
    SaveComment: "Save",
    CancelComment: "Cancel",
    UnwrapComment: "Unwrap",
    InsertPI: "Insert PI",
    SavePI: "Save",
    CancelPI: "Cancel",
    UnwrapPI: "Unwrap",
    CutXML: "Cut",
    CopyXML: "Copy",
    PasteXML: "Paste",
    ClearXML: "Clear",
    DeleteXML: "Delete",
    WrapXML: "Wrap",
    PIHeading: "PI",
}

export const Constants = {
    
    
    NO_SELECTION: 'NO_SELECTION',
    CUT: 'CUT',
    COPY: 'COPY',
    PASTE: 'PASTE',
    DELETE: 'DELETE',
    WRAP: 'WRAP'
}

export const Settings = {
    SHOW_CLOSING_TAG : false,
    PREFIX_TWO_LINES : true,
}